name: CI
on: [push, pull_request]
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run prettier:check
      - run: npm run lint:check
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*', 'current']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run test:ci
      - run: npm install codecov -g
        if: ${{ matrix.node-version == 'current' }}
      - run: codecov -f ./coverage/clover.xml -t ${{ secrets.CODECOV_TOKEN }} --commit=$GITHUB_SHA --branch=${GITHUB_REF##*/}
        if: ${{ matrix.node-version == 'current' }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci --ignore-scripts
      - run: npm run build:es2015
      - run: npm run build:esm5
      - run: npm run build:cjs
      - run: npm run build:umd
      - run: npm run build:types
